cmd_drivers/gpu/mali/mali/__malidrv_build_info.o := arm-linux-gnueabihf-gcc -Wp,-MD,drivers/gpu/mali/mali/.__malidrv_build_info.o.d  -nostdinc -isystem /usr/lib/gcc/arm-linux-gnueabihf/4.6/include -I/home/tyler/dev/rk3188/tylermk908/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-rk3188/include -Iarch/arm/plat-rk/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -Idrivers/gpu/mali/mali/linux/license/gpl -DPROFILING_SKIP_PP_JOBS=0 -DPROFILING_SKIP_PP_AND_GP_JOBS=0 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP=0 -DMALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED=0 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS=0 -DMALI_STATE_TRACKING=1 -DMALI_OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB=16 -DUSING_GPU_UTILIZATION=1 -DMALI_UPPER_HALF_SCHEDULING -Idrivers/gpu/mali/mali -Idrivers/gpu/mali/mali/include -Idrivers/gpu/mali/mali/common -Idrivers/gpu/mali/mali/linux -Idrivers/gpu/mali/mali/platform -DSVN_REV_STRING=\"-3195dd7\"  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(__malidrv_build_info)"  -D"KBUILD_MODNAME=KBUILD_STR(mali)" -c -o drivers/gpu/mali/mali/__malidrv_build_info.o drivers/gpu/mali/mali/__malidrv_build_info.c

source_drivers/gpu/mali/mali/__malidrv_build_info.o := drivers/gpu/mali/mali/__malidrv_build_info.c

deps_drivers/gpu/mali/mali/__malidrv_build_info.o := \

drivers/gpu/mali/mali/__malidrv_build_info.o: $(deps_drivers/gpu/mali/mali/__malidrv_build_info.o)

$(deps_drivers/gpu/mali/mali/__malidrv_build_info.o):
